import pandas as pd
import os

# Create sample product catalog data
catalog_data = [
    {
        "Product_ID": "D001",
        "Name": "Rosemary Floral Sundress",
        "Category": "Dress",
        "Price": 85,
        "Available_Sizes": "XS,S,M,L,XL",
        "Fit": "Relaxed",
        "Color": "Pink",
        "Pattern": "Floral",
        "Sleeve_Length": "Sleeveless",
        "Neckline": "V-neck",
        "Length": "Knee-length",
        "Occasion": "Casual",
        "Season": "Summer",
        "Brand": "SunnyDays",
        "Description": "Light and airy floral sundress perfect for summer occasions"
    },
    {
        "Product_ID": "D002", 
        "Name": "Daisy Print Midi Dress",
        "Category": "Dress",
        "Price": 90,
        "Available_Sizes": "S,M,L,XL",
        "Fit": "Relaxed",
        "Color": "Yellow",
        "Pattern": "Floral",
        "Sleeve_Length": "Sleeveless",
        "Neckline": "Round neck",
        "Length": "Midi",
        "Occasion": "Casual",
        "Season": "Summer",
        "Brand": "FloralFashion",
        "Description": "Cheerful daisy print midi dress with comfortable fit"
    },
    {
        "Product_ID": "B001",
        "Name": "Classic Navy Blazer",
        "Category": "Blazer",
        "Price": 120,
        "Available_Sizes": "XS,S,M,L,XL,XXL",
        "Fit": "Tailored",
        "Color": "Navy",
        "Pattern": "Solid",
        "Sleeve_Length": "Long sleeve",
        "Neckline": "Collared",
        "Length": "Hip-length",
        "Occasion": "Formal",
        "Season": "All",
        "Brand": "Professional",
        "Description": "Timeless navy blazer for professional settings"
    },
    {
        "Product_ID": "T001",
        "Name": "Casual Cotton T-Shirt",
        "Category": "Top",
        "Price": 25,
        "Available_Sizes": "XS,S,M,L,XL,XXL",
        "Fit": "Relaxed",
        "Color": "White",
        "Pattern": "Solid",
        "Sleeve_Length": "Short sleeve",
        "Neckline": "Round neck",
        "Length": "Hip-length",
        "Occasion": "Casual",
        "Season": "All",
        "Brand": "BasicWear",
        "Description": "Comfortable cotton t-shirt for everyday wear"
    },
    {
        "Product_ID": "D003",
        "Name": "Elegant Black Evening Dress",
        "Category": "Dress",
        "Price": 150,
        "Available_Sizes": "XS,S,M,L,XL",
        "Fit": "Bodycon",
        "Color": "Black",
        "Pattern": "Solid",
        "Sleeve_Length": "Sleeveless",
        "Neckline": "V-neck",
        "Length": "Maxi",
        "Occasion": "Formal",
        "Season": "All",
        "Brand": "ElegantEvening",
        "Description": "Sophisticated black dress perfect for formal events"
    },
    {
        "Product_ID": "J001",
        "Name": "High-Waisted Skinny Jeans",
        "Category": "Jeans",
        "Price": 65,
        "Available_Sizes": "24,26,28,30,32,34",
        "Fit": "Slim",
        "Color": "Blue",
        "Pattern": "Solid",
        "Sleeve_Length": "N/A",
        "Neckline": "N/A",
        "Length": "Full-length",
        "Occasion": "Casual",
        "Season": "All",
        "Brand": "DenimCo",
        "Description": "Classic high-waisted skinny jeans in dark wash"
    },
    {
        "Product_ID": "S001",
        "Name": "Flowy Maxi Skirt",
        "Category": "Skirt",
        "Price": 45,
        "Available_Sizes": "XS,S,M,L,XL",
        "Fit": "Relaxed",
        "Color": "Mint Green",
        "Pattern": "Solid",
        "Sleeve_Length": "N/A",
        "Neckline": "N/A",
        "Length": "Maxi",
        "Occasion": "Casual",
        "Season": "Summer",
        "Brand": "FlowingFashion",
        "Description": "Comfortable maxi skirt with elastic waistband"
    },
    {
        "Product_ID": "A001",
        "Name": "Athletic Yoga Set",
        "Category": "Activewear",
        "Price": 55,
        "Available_Sizes": "XS,S,M,L,XL",
        "Fit": "Athletic",
        "Color": "Black",
        "Pattern": "Solid",
        "Sleeve_Length": "Long sleeve",
        "Neckline": "Round neck",
        "Length": "Full-length",
        "Occasion": "Workout",
        "Season": "All",
        "Brand": "FitLife",
        "Description": "High-performance yoga set with moisture-wicking fabric"
    },
    {
        "Product_ID": "D004",
        "Name": "Bohemian Maxi Dress",
        "Category": "Dress",
        "Price": 95,
        "Available_Sizes": "S,M,L,XL",
        "Fit": "Relaxed",
        "Color": "Multi",
        "Pattern": "Paisley",
        "Sleeve_Length": "Long sleeve",
        "Neckline": "V-neck",
        "Length": "Maxi",
        "Occasion": "Casual",
        "Season": "Fall",
        "Brand": "BohoChic",
        "Description": "Free-spirited maxi dress with paisley print"
    },
    {
        "Product_ID": "T002",
        "Name": "Pastel Pink Blouse",
        "Category": "Top",
        "Price": 40,
        "Available_Sizes": "XS,S,M,L,XL",
        "Fit": "Tailored",
        "Color": "Light Pink",
        "Pattern": "Solid",
        "Sleeve_Length": "Short sleeve",
        "Neckline": "Button-up",
        "Length": "Hip-length",
        "Occasion": "Business Casual",
        "Season": "Spring",
        "Brand": "ProfessionalPastels",
        "Description": "Soft pink blouse perfect for office wear"
    }
]

# Create DataFrame and save to Excel
df = pd.DataFrame(catalog_data)
os.makedirs('data', exist_ok=True)
df.to_excel('data/Apparels_shared.xlsx', index=False)
print("Sample catalog created successfully!") 